### ISSUE TITLE
snapshot scores

### ISSUE THREAD

**Issue by aramgrigoryan** [boombatower/tumbleweed-cli#20]
Is it possible do add an option to also show the stability score for each snapshot in the list?

**Comment by ProgrammerPolymathic** [comment]
At the risk of being accused of self-advertising, I'll point to Issue #16 since there hasn't been any response to either this issue or that one, and `twups` was made to provide precisely what you're asking for.

While I still have a list of things to refine (like setting custom score cutoffs), I've been using it daily since posting that issue without problems, so I can vouch for its reliability.

**Comment by aramgrigoryan** [comment]
> At the risk of being accused of self-advertising, I'll point to Issue #16 since there hasn't been any response to either this issue or that one, and `twups` was made to provide precisely what you're asking for.
> 
> While I still have a list of things to refine (like setting custom score cutoffs), I've been using it daily since posting that issue without problems, so I can vouch for its reliability.

thanks

**Comment by boombatower** [comment]
Yeah, something I had always planned on doing boombatower/tumbleweed-review#5, but never got back to it. I'll have to take a look at twups. I could review a PR on either end to merge things together.

**Comment by boombatower** [comment]
Lets keep the conversation in #16.
